### ISSUE TITLE
Proposed method

### ISSUE THREAD

**Issue by Semisol** [BreMea/AutoUOC#3]
OPTIONAL SUGGESTIONS:
- We should add an optional website module, because why not.
- Auto image hosting: If an image link is posted to complete, it should create a Scratch project, set the thumbnail and notify the person that the image has been hosted. (irrelevant but might be useful)
- Latest UOC: A feature that edits the user's About Me to include the latest UOC.
- Order ID's. Would make things SO MUCH EASIER. Like. `Claimed #1.` or `#1 has been completed. <more information>` or `#1 is invalid 
because <reason>`
- User Notifications: The bot should notify the users that their order has been completed and link the post. `Your order #1 has been completed at <post link>`
- Studio Logging: This allows any actions like invalidating an order, claiming or completion (+ unclaiming if you can't do it?) to be logged in a studio or optionally the description. And maybe the title to show stats.

#1: Notification count 0<
#2: Check all notifications and mark as read
#3: Check all pages from the last checked page (inclusive) and the last page (inclusive)
#4: If any orders are found matching a format, such as starting with the line `ORDER`, edit the existing UOC or add to a new one if it has been n time.
#5: Parse commands.

**Comment by bremea** [comment]
Hey, these are great! I want to focus on the minimum viable product for now: an auto-updating UOC that can be customized. Once we’re finished and have released the basics we can get to work on some of this! There’s some other parts of shops I think could be really interesting to automate, so this list will probably update in the future :)

**Comment by Semisol** [comment]
@BreMea You want to know what I am working on?

**Comment by Semisol** [comment]
Rewriting the request forums, so it is more user friendly.

**Comment by Semisol** [comment]
Also, you want to help with that? @BreMea

**Comment by bremea** [comment]
Sure!

**Comment by Semisol** [comment]
@BreMea Dead project?

**Comment by bremea** [comment]
> @BreMea Dead project?

Nope, but I set it aside for a little bit to focus on something else. Development is still continuing, though.

**Comment by Semisol** [comment]
okay

**Comment by pikachub2005** [comment]
What's the request to post something on a forum page?

**Comment by cobaltt7** [comment]
The bot has been banned from scratch.


________________________________

**Comment by pikachub2005** [comment]
I wasn't going to make a bot

**Comment by pikachub2005** [comment]
ST doesn't like bots doing social actions, I'm aware

**Comment by pikachub2005** [comment]
Guess I'll just post something and figure it out myself 🙄

**Comment by pikachub2005** [comment]
> The bot has been banned from scratch.
> […].

So posting to the topic returns a 302 with a location for the post. Should I post it again to the location orr what (idk what I'm doing, okay? I'm only 16)

**Comment by bremea** [comment]
This is not a thread for you to get support for breaking Scratch ToS. Please go somewhere else.

**Comment by Semisol** [comment]
> This is not a thread for you to get support for breaking Scratch ToS. Please go somewhere else.

Should we archive the project?

**Comment by pikachub2005** [comment]
> This is not a thread for you to get support for breaking Scratch ToS. Please go somewhere else.

I wasn't doing anything with bots, I was going to use it in a website so you can change scratch stuff. 
<sub><sup>https://scratchdb.lefty.one/v3/forum/user/history/Raihan142857 is becuase of a bot</sup></sub>
